#! /usr/bin/groovy
pipeline{
    agent any
    stages{
        stage("Test"){
            steps{
                unitTesting()
            }
        }
        stage("Coverage"){
            steps{
                 echo("Deploying")
            }
        }

        stage("Deploy"){
            steps(){
                echo("Deploying")
            }
        }
    }
}

def unitTesting(){
    readpom = readMavenPom file: 'project/newapi/pom.xml'
    sh "mvn clean test project/newapi/pom.xml"
}
