#! /usr/bin/groovy
pipeline{
    agent any
    stages{
        stage("Test"){
            steps{
                echo("Testing")
                unitTest()
               
            }
        }
        stage("Coverage"){
            steps{
                 echo("Deploying")
            }
        }

        stage("Deploy"){
            steps(){
                echo("Deploying")
            }
        }
    }
}

def unitTest(){
    dir('newapi'){
        sh 'mvn clean test'
    }
}
